version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.1
    working_directory: ~/collijion

    environment:
      LEIN_ROOT: "true"
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}

      # Check deps
      - run: lein deps
      # Check code formatting
      - run: lein cljfmt check

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      # run tests!
      - run: lein test